# Generated by Django 3.1.2 on 2020-10-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoritefood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoritetoy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
